newrelic/newrelic-jfr-core

.github/workflows/gradle.yml, .github/workflows/publish_master_merge.yml, .github/workflows/pull_request.yml
Dummy commit, dummy PR to test GH actions.
=> test github actions

gradle.properties
Cutting an initial release now.
=> release v0.1.0

.github/workflows/publish_master_merge.yml, build.gradle.kts
=> add artifact signing

build.gradle.kts, src/main/java/com/newrelic/jfr/MethodSupport.java, src/main/java/com/newrelic/jfr/ToEventRegistry.java, src/main/java/com/newrelic/jfr/ToMetricRegistry.java, src/main/java/com/newrelic/jfr/Workarounds.java, src/main/java/com/newrelic/jfr/toevent/EventToEvent.java, src/main/java/com/newrelic/jfr/tometric/EventToMetric.java, src/main/java/com/newrelic/jfr/tosummary/EventToSummary.java
=> add details to pom and fix javadocs

.github/workflows/snyk.yml, jfr-daemon/build.gradle.kts
Now that this is a multi-module project, I noticed this in the snyk output:
So this should fix that up and improve our coverage.
=> add subproject support for snyk

build.gradle.kts, jfr-daemon/build.gradle.kts, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/DaemonConfig.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EnvironmentVars.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRController.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRJMXConnector.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRJMXRecorder.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/TelemetryClientFactory.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/VersionFinder.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/DaemonConfigTest.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/JFRControllerTest.java
This resolves #36 with one caveat -- the remote system property is not yet being read.  
I'm happy to file a specific issue for that as a follow-up/future task if that makes sense.
=> Begin config

README.md, gradle.properties
Also enhances the README to document with available env vars for the daemon
=> release 0.2.0

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/FileToBufferedTelemetry.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/main/resources/log4j2.xml
We also swap to logging on STDERR as that's what the Infra agent expects
=> Turn down the logging level and reduce noise

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRDaemon.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/lifecycle/RemoteEntityGuid.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/lifecycle/RemoteEntityGuidTest.java
Remove a few unsightly null checks in favor of `Optional<String>` usage.
=> Prefer optional for guid

CHANGELOG.md, gradle.properties
=> begin version 0.5.0

README.md
=> fix event endpoint in readme

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/TelemetryClientFactory.java
=> change calls to eliminate deprecation warnings.

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EventConverter.java
=> cleanup log statement

.github/workflows/publish_main_snapshot.yml, .github/workflows/publish_release.yml, .github/workflows/pull_request.yml, README.md
this addresses #107 and adds EU endpoints to the readme
=> add EU endpoints to readme

gradle.properties, jfr-daemon/build.gradle.kts, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/BufferedTelemetry.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/DaemonConfig.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EventConverter.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/OkHttpPoster.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/RecordedEventBuffer.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/SetupUtils.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/VersionFinder.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/agent/AgentMain.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/agent/FileJfrRecorder.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/agent/FileJfrRecorderFactory.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/app/JFRDaemon.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/app/JmxJfrRecorder.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/app/JmxJfrRecorderFactory.java, jfr-jlink/build.gradle.kts
Builds of [PR 142](https://github.com/newrelic/newrelic-jfr-core/pull/142) and backports the `jfr-daemon` to use java 8.
=> backport jfr-daemon to java 8

jfr-daemon/build.gradle.kts
=> publish javadocs and sources. Create shadowJar instead of jar

CHANGELOG.md, README.md, gradle.properties
Hold this PR until after the 1.1.0 release.
=> Update documentation for 1.1.0 release

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, smoke-tests/build.gradle.kts
left over unused local variables, was there for testing purposes.
=> removed unused left overs

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EventConverter.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java
These 3 logs repeat every 10 seconds. This would appear to be better scoped as debug IMO
=> Debug log JFRUploader batch sizes

CONTRIBUTING.md
docs: update slack invite link NR-72269
=> docs: update slack invite link NR-72269

README.md
=> Update README.md to conform with repo stds

.github/workflows/snyk.yml
updated the snyk dependency scan workflow to be run on a weekly schedule or to be triggered manually
[Issue #1344](https://github.com/newrelic/newrelic-java-agent/issues/1344)
=> Updated Snyk Dependency Scan Workflow

.github/workflows/snyk_scan.yml
added snyk dependency scanning on push to main
=> renamed file and added scanning on push to main

README.md
=> Updating community URL
