newrelic/newrelic-jfr-core

src/main/java/com/newrelic/jfr/ToMetricRegistry.java, src/test/java/com/newrelic/jfr/ToMetricRegistryTest.java
In trying to use this in another component, it was discovered that individual mappers in this registry are not exposed.  This prevents the streaming JFR user from setting up callbacks for all known supported types.  The `ToMetricRegistry.all()` method now exposes this.
This was also an opportunity to simplify away from the `Map` which used redundant names.  The registry is considered configuration and is not expected to be used in the critical path, which is why the `List` suffices.  If a user intends to violate this, they can still build their own map by leveraging the stream (but it should be discouraged).
=> Expose all mappers in the registry

src/main/java/com/newrelic/jfr/ToSummaryRegistry.java, src/test/java/com/newrelic/jfr/ToSummaryRegistryTest.java
This changes the shape of the `ToSummaryRegistry` to look more like the `ToMetricRegistry`, but also needed to expose all mappers for users to hook up for streaming JFR.
=> Expose summary mappers

README.md, THIRD_PARTY_NOTICES.md
This resolves #39.
There is probably lots of room remaining to improve the documentation here, but this should now support the multi-module repo layout and removes references to the old name.
=> update readme and references to repo name.

jfr-mappers/src/main/java/com/newrelic/jfr/MethodSupport.java, jfr-mappers/src/test/java/com/newrelic/jfr/MethodSupportTest.java
Added some tests to the fix overflow PR, but did it as a new branch to facilitate easier step-by-step reviewing.  I think it'll make the most sense to go commit by commit to see what I did at each point.
I was able to craft a test that exercised the `IOException` edge case.  I the fixed the code and broke the passing test and then removed the exception.
The short story is that I think that the edge case was due to an error -- we were using the size of the stack frames map to determine the new limit, instead of using the computed desired frame count.  I removed the conditional and exception because it truly shouldn't happen anymore.  😉
=> Fix overflow tests

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRController.java, jfr-mappers/src/main/java/com/newrelic/jfr/MethodSupport.java, jfr-mappers/src/test/java/com/newrelic/jfr/MethodSupportTest.java
When running the JFR daemon in an Ubuntu or Alpine container on an Amazon EC2 instance, the JRE inside the container can't resolve the short hostname it receives to do a reverse DNS lookup. This detects failure of `getLocalHost()` and just puts in a localhost IP address.
You probably don't want to accept this PR, since it has a hard-coded IP address in it. I'd love to see how _you'd_ do the same thing.
=> Fallback for localIpAddr failure

jfr-mappers/src/main/java/com/newrelic/jfr/tometric/ThreadAllocationStatisticsMapper.java, jfr-mappers/src/test/java/com/newrelic/jfr/tometric/ThreadAllocationStatisticsMapperTest.java
We have observed at least one JVM in the wild that, under some circumstance, returns null for the thread field.  
In that rare case, let's just guard against that and return just the allocation data without thread identifiers.
=> guard against null thread

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRCommonAttributes.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRDaemon.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/JFRCommonAttributesTest.java
This resolves #60 
We only set the `app.name` common attr now if the entity guid is missing.  When it is present, it will be stitched up by the backend platform.
=> No app name if agent

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRDaemon.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/JFRUploaderTest.java
This resolves #73 .
It reads a little silly because the entity guid fetching is blocking/synchronous...but it sets the stage for the next change, which will cause the entity guid fetching to be done on its own background thread.  After that, this will make more sense.
Note: This is built on top of #74 and will need a rebase (so probably don't bother reviewing until that one is merged)
=> Gate on readiness check for entity guid

.github/workflows/publish_main_snapshot.yml, .github/workflows/publish_release.yml, CHANGELOG.md, build.gradle.kts, gradle.properties
I think that we prefer to initiate releases with a github release, so let's adopt that here for this repo.
I also added a changelog.
=> Standardize release process

build.gradle.kts
The snapshot suffix was not being added to the output artifact names, and that's why the uploads were failing with HTTP 400.  This adds those suffixes back (unless `-Prelease=true`)
=> fix publishing snapshot builds.

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRController.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRJMXRecorder.java
This fixes #65.  
It is potentially risky to send the local config options over to the remote.  Instead, let's just invoke the remote method that chooses the default profile.
Also simplifies some exception handling along the way.
=> use setPredefinedConfiguration

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/JFRUploaderTest.java
Because each temp file is created in a temp directory, we need to also clean up the temp directory.
=> Ensure that dir of temp file is also deleted.

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRDaemon.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/RecordedEventBuffer.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/RecordedEventBufferTest.java
While troubleshooting a separate issue, it was discovered that the writing of the `Queue<RecordedEvent>` happens on the same thread that reads from that queue (to drain it).  As a result, in the event that a file had a very large number of events (> 50,000), the queue would be full and the `.put()` would cause that thread to block and never recover (because no other threads read from the queue).  
The fix here is to increase the default max queue size to 250k (5x increase) and use `.offer()` instead of `.put()`.  If the offer fails, we log a warning, break out of the file loop, and drop all the remaining events from this file.  The queue will then be drained, and we will pick back up with the next file 10 seconds later.
=> Improve queue handling

jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EventConverter.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/JFRUploader.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/EventConverterTest.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/AbstractThreadDispatchingSummarizer.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/EventToSummary.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/G1GarbageCollectionSummarizer.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/PerThreadNetworkReadSummarizer.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/PerThreadNetworkWriteSummarizer.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/PerThreadObjectAllocationInNewTLABSummarizer.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/PerThreadObjectAllocationOutsideTLABSummarizer.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/G1GarbageCollectionSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/NetworkReadSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/NetworkWriteSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/ObjectAllocationInNewTLABSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/ObjectAllocationOutsideTLABSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/PerThreadObjectAllocationInNewTLABSummarizerTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/PerThreadObjectAllocationOutsideTLABSummarizerTest.java
Context: The jfr daemon was causing an increase in network activity over time. The network points of the daemon are the following:
- streaming data from JFR on the service being monitored to the daemon
- writing that stream to a file
- loading that file back to the daemon
- sending events and metrics to New Relic
After eliminating the streaming and file writing and read as the source of the issue, it pointed me to the sending of events/metrics to NR. Looking at one of the test apps it was clear that over time more and more metrics were getting sent each harvest cycle (10 seconds). 
Issue: In some of our summarizers (i.e. ObjectAllocationInNewTLABSummarizer) we keep track of all summarizers in a map based on thread name so we can recall them when reporting data and don't have to recreate …
=> Fix network issue

jfr-mappers/src/main/java/com/newrelic/jfr/MethodSupport.java, jfr-mappers/src/main/java/com/newrelic/jfr/ToEventRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/toevent/ValhallaVBCDetector.java, jfr-mappers/src/test/java/com/newrelic/jfr/toevent/ValhallaVBCDetectorTest.java
This small change adds support for a new type event that is only present in Java 16 and above. It has no impact on anyone not running a Java 16 beta (and even then, requires a command-line flag to be present before these events are generated).
=> Add support for Valhalla VBC events

jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/BaseDurationSummarizer.java
Changing the duration name to an empty string caused a lot of errors to occur. This reverts that change.
=> revert empty string back to null

README.md, gradle.properties, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/DaemonConfig.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EnvironmentVars.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/SetupUtils.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/app/JmxJfrRecorderFactory.java, smoke-tests/build.gradle.kts
JFRD will accept a New Relic license key or the Insights Insert Key. 
Confirmed with manual testing -  Resolves #156 
Throw exception and shutdown JFRD if target does not have the Flight Recorder MBean.  The output to the user is clearer. Resolves #162 
```
[main] ERROR com.newrelic.jfr.daemon.app.JFRDaemon - JFR Daemon is crashing!
com.newrelic.jfr.daemon.JfrRecorderException: Failed to obtain JfrRecorder.
at com.newrelic.jfr.daemon.app.JmxJfrRecorderFactory.getRecorder(JmxJfrRecorderFactory.java:53)
at com.newrelic.jfr.daemon.JfrController.resetJfrRecorder(JfrController.java:79)
at com.newrelic.jfr.daemon.JfrController.loop(JfrController.java:60)
at com.newrelic.jfr.daemon.app.JFRDaemon.main(JFRDaemon.java:58)
Caused by: javax.management.InstanceNotFoundException: …
```
=> add support for license key.  update doc for proxy

jfr-daemon/build.gradle.kts
This will package the daemon jar into the jfr-agent-extension, so that the extension works and can attach. Thanks @jack-berg  for finding the solution!
The snyk security issue is a test issue and will be fixed when #163  is merged.
=> enable jar task for daemon

README.md, jfr-mappers/build.gradle.kts, jfr-mappers/src/main/java/com/newrelic/jfr/ToSummaryRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/tosummary/BasicGarbageCollectionSummarizer.java, jfr-mappers/src/test/java/com/newrelic/jfr/tosummary/BasicGarbageCollectionSummarizerTest.java
Adds `BasicGarbageCollectionSummarizer` to create `jfr.GarbageCollection.minorDuration` and `jfr.GarbageCollection.majorDuration` metrics. These metrics include the count.
```
{
"app.name": "jfr-daemon",
"collector.name": "JFR-Uploader",
"endTimestamp": 1615421055034,
"entity.guid": "MjIxMjg2NHxFWFR8U0VSVklDRXwtODc2Mzc1ODMwMzk3NDAwNDM2OQ",
"entity.name": "jfr-daemon",
"host.hostname": "C02XQ1RKJG5J/192.168.1.23",
"instrumentation.name": "JFR",
"instrumentation.provider": "JFR-Uploader",
"jfr.GarbageCollection.minorDuration": {
"type": "summary",
"count": 490,
"sum": 1202,
"min": 0,
"max": 11
},
"metricName": "jfr.GarbageCollection.minorDuration",
"newrelic.source": "metricAPI",
"nr.entity.type": "SERVICE",
"service.name": "jfr-daemon",
"timestamp": 1615421045052
}
```
```
{
"app.name": …
```
=> Add basic gc summarizer

README.md
Clearer instructions on how to adjust log levels in jfr daemon and expectations.  
Since the daemon and the telemetry SDK both use slf4j-simple, the log level is adjusted via configuring slf4j according to its documentation.
=> improve readme for logging

jfr-mappers/src/main/java/com/newrelic/jfr/ToEventRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/toevent/AttributeValueSplitter.java, jfr-mappers/src/main/java/com/newrelic/jfr/toevent/JVMSystemPropertyMapper.java, jfr-mappers/src/test/java/com/newrelic/jfr/toevent/AttributeValueSplitterTest.java, jfr-mappers/src/test/java/com/newrelic/jfr/toevent/JVMSystemPropertyMapperTest.java
This is for #92 . 
The New Relic Event API has a limit of 4096 characters for attribute values.  Events with attribute values > 4096  are dropped by the backend and a NR Integration Error is created instead. Unfortunately, the user has no way of knowing this was dropped unless they query for this error in their account.
Some values from JFR Recorded Events end up being over 4096 characters and are dropped. For example, jfr event `jdk.InitialSystemProperty` and the value for key `java.class.path` will easily exceed 4096 characters. See the issue for an example of this value. 
The approach taken here is to split the values and create additional `Extended` attributes. Link to slack discussion about this approach is in the issue. 
```
{
"collector.name": "JFR-Uploader",
"entity.guid": …
```
=> Split large attribute values

build.gradle.kts, jfr-mappers/src/main/java/com/newrelic/jfr/ProfilerRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/ToEventRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/ToMetricRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/ToSummaryRegistry.java, jfr-mappers/src/main/java/com/newrelic/jfr/profiler/ProfileSummarizer.java, jfr-mappers/src/test/java/com/newrelic/jfr/profiler/ProfileSummarizerTest.java
Gradle deprecation warnings caused by google-java-format-gradle-plugin version 8.0.
Upgraded google-java-format-gradle-plugin version to 9.0 which resolves the gradle deprecation warning.
Ran google-java-format-gradle-plugin to apply new formatting rules.
Addressing:
https://github.com/newrelic/newrelic-jfr-core/issues/21
https://github.com/sherter/google-java-format-gradle-plugin/issues/41
Tested:
Ran `./gradlew build --warning-mode all` locally and reviewed logs.
Logs showing no gradle deprecation warnings.
=> Issue #21 - Resolve gradle deprecation warnings.

CHANGELOG.md, README.md, gradle.properties, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/AttributeNames.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/DaemonConfig.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EnvironmentVars.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/EventConverter.java, jfr-daemon/src/main/java/com/newrelic/jfr/daemon/SetupUtils.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/DaemonConfigTest.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/EventConverterTest.java, jfr-daemon/src/test/java/com/newrelic/jfr/daemon/SetupUtilsTest.java
To properly support JFR in stand alone mode, this PR adds support for the `service.instance.id` value, which is required by the back-end if the `entity.guid` value is absent. (`entity.guid` is present when running JFR from [within the NR APM agent](https://github.com/newrelic/newrelic-jfr-core/blob/main/README.md#new-relic-java-agent-jfr-service)).
The `service.instance.id` will be configured from one of the following sources, in order of precedence:
- If the environment variable `OTEL_RESOURCE_ATTRIBUTES` is present and contains the key `service.instance.id`, the value assigned to this  key will be used. For example, a value of `service.name=myApp,deployment.environment=production,service.version=1.0,service.instance.id=abcd` would
assign the `service.instance.id` value to `abcd`.
- If …
=> Add service.instance.id configuration support for JFR stand alone
